timezone: America/New_York

# Dependencies
kramdown:
	input: GFM
	syntax_highlighter: rouge 
#markdown:         redcarpet
#redcarpet:
#  extensions: ["tables", "footnotes"]

#highlighter:         pygments

# Permalinks
permalink:        pretty

# Setup
title:            Transient Dynamic
tagline:          'Computational Science, Dynamical Systems, Literate Modeling, Complex Systems, Informatics'
url:              http://robclewley.github.io
shorturl:         robclewley.github.io

author:
  name:           'Rob Clewley'
  url:            https://twitter.com/robclewley
copyright:        2015


paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           github.com/robclewley/robclewley.github.io


# This is the list of pages to include in the header of the website.
pages_list:
  About: '/about/'
  Archive: '/archive/'
  Tagged: '/tagged/'
  Feed: '/atom.xml'

# Allow URL Redirects:
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-gist
